/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, forwardRef } from "react";
import {
  useGLTF,
  MeshTransmissionMaterial,
  Caustics,
  MeshRefractionMaterial,
} from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
// import headphonesModel from "./assets/headphones1.glb";

export default function Headphones(props) {
  const { nodes, materials } = useGLTF(props.model);
  const modelRef = useRef();

  useFrame((state, delta) => {
    modelRef.current.rotation.y += 0.01;
  });

  return (
    <group ref={modelRef} {...props} dispose={null}>
      <mesh
        name="base"
        castShadow
        receiveShadow
        geometry={nodes.base.geometry}
        material={materials["Material.001"]}
        position={[-0.025, 1.077, 0]}
        scale={[0.164, 0.15, 0.369]}
      />

      <mesh
        name="glass"
        castShadow
        receiveShadow
        geometry={nodes.glass.geometry}
        rotation={[-Math.PI, 0, -Math.PI / 2]}
        scale={[-1, -0.196, -1]}
      >
        <MeshTransmissionMaterial
          thickness={0.5}
          chromaticAberration={0.05}
          anisotropy={1}
          clearcoat={0.5}
          clearcoatRoughness={0.2}
          envMapIntensity={1}
        />
      </mesh>

      <mesh
        name="cushion"
        castShadow
        receiveShadow
        geometry={nodes.cushion.geometry}
        material={materials.Material}
        position={[-0.515, 0, 0.008]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.554, 0.474, 0.554]}
      />
      <mesh
        name="base-extend"
        castShadow
        receiveShadow
        geometry={nodes["base-extend"].geometry}
        material={materials["Material.001"]}
        position={[-0.076, 1.575, 0]}
        rotation={[0, 0, 0.214]}
        scale={[-0.093, -0.423, -0.199]}
      />
      <mesh
        name="circle"
        castShadow
        receiveShadow
        geometry={nodes.circle.geometry}
        material={materials["Material.001"]}
        position={[-0.212, 0, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.833, 1.039, 0.833]}
      ></mesh>
      <mesh
        name="sphere"
        castShadow
        receiveShadow
        geometry={nodes.sphere.geometry}
        material={materials["Material.007"]}
        position={[0, -0.834, 0]}
        rotation={[-0.43, -0.016, -0.014]}
        scale={0.172}
      />
      <mesh
        name="sphere-2"
        castShadow
        receiveShadow
        geometry={nodes["sphere-2"].geometry}
        material={materials["Material.004"]}
        position={[0, -0.766, 0.352]}
        rotation={[-0.43, -0.016, -0.014]}
        scale={0.172}
      />
      <mesh
        name="sphere-3"
        castShadow
        receiveShadow
        geometry={nodes["sphere-3"].geometry}
        material={materials["Material.006"]}
        position={[0, -0.778, -0.367]}
        rotation={[-0.43, -0.016, -0.014]}
        scale={0.172}
      />
    </group>
  );
}

// useGLTF.preload(headphonesModel);
